name: Build , Test & Deploy
on: [push, pull_request]
jobs:
  Build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install 
          npm run build

      - name: Run Unit Test
        run: npx jest --coverage

  Deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Deploy to Production
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE}}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID}}
